### ISSUE TITLE
Equivalent to `partial.lenses.valueOr`?

### ISSUE THREAD

**Issue by rjhilgefort** [akheron/optics-ts#2]
Hello! Thanks for the awesome library. I'm a long time user of `partial.lenses` and am trying to find a TS alternative. In converting some code to `optics-ts` and am having some trouble understanding how to make an equivalent to `valueOr`. Is it possible with this library and/or with TS?

https://github.com/calmm-js/partial.lenses#l-valueor

Thanks in advance and thanks again for all the work on this project!

**Comment by lanyusan** [comment]
I just did some testing of optics-ts. `preview` is maybe what you wanted:

```
  it('optics-ts', () => {
    const optics = O.optic<any>()
      .path(['m', 'n', 'names'])
      .elems()
      .when((name: any) => name.id === id)
    let r = undefined
    const fn = () => (r = O.preview(optics)(data))
    run(fn)
    expect(r).toEqual({ id, name })
  })

```

**Comment by akheron** [comment]
There's currently no equivalent for `valueOr`, but it should be easy to add. I'll give it a shot sometime soon.

**Comment by rjhilgefort** [comment]
🙏 @akheron thanks for the reply! I'm happy to tinker and try to help add some lenses as I use this library anymore. I read through the docs, but I'm not sure I understand how I would even approach making a new optic like this. If you have any tips, I'll play around and try to make some of the other optics I need and try to PR them back to this repo. Cheers!

**Comment by akheron** [comment]
I added `.valueOr()`. You can try it out by `npm install optics-ts@next`. I'll make an official release of 1.1.0 with all the new stuff once I've confirmed that everything works for my own use cases :)

**Comment by akheron** [comment]
What comes to adding new optics, the process goes like this:

- Implement the optic in `src/internals.ts`. There are plenty of examples of all kinds of optics there. It's probably best to use the `iso()`, `lens()` and `prism()` primitives and perhaps `compose()` to build more complex optics. The primitives take as arguments 2 functions: The first one is used in the reading direction, and the second one in the writing direction.
- Also add it to the `Optic` class near the end of `src/internals.ts`
- Think of what happens to the focus type `A` when this new optic is applied to it. Also think of what happens when some type `B` is written through this optic. These determine what to use as the `A` and `T` type parameters of the new optic, respectively. Refer to `src/hkt.ts` for how to construct the `T` parameter. The syntax might seem a bit odd, but in short, `this[1]` refers to the written type `B` and the `0` slot is the output/result type of the type operators. 
- Determine the type of your new optic (it's probably clear from the implementation)
- Add a new entry to `scripts/generate-index.ts`. There's a string template for each optic type. The `composition` function used to build the optic's output type takes `T` as the first argument and the new focus type `A` as the second argument. The script takes care of generating correct composition types.
- Add tests to `tests/optic.spec.ts`

After writing this, I'm not sure this makes it any clearer how to add new optics. Don't hesitate to ask more questions :)

**Comment by rjhilgefort** [comment]
> I added .valueOr(). You can try it out by npm install optics-ts@next. I'll make an official release of v1.1.0 with all the new stuff once I've confirmed that everything works for my own use cases :)

Thank you!! Much appreciated!

> After writing this, I'm not sure this makes it any clearer how to add new optics. Don't hesitate to ask more questions :)

Better than nothing! Thanks for the write up- I'll give it a shot next time I need one that doesn't exist. Thanks again for the quick replies and again for the effort on a type-safe optics library!

**Comment by akheron** [comment]
V1.1.0 was released some time ago with `valueOr`.

**Comment by rjhilgefort** [comment]
Thank you!
