### ISSUE TITLE
Setting property with value of empty object within list should not be undefined

### ISSUE THREAD

**Issue by aaschmid** [akheron/optics-ts#237]
I created the reproducer in jest below to should what I want to achieve using v2.3.0:

```typescript
    describe("reproducer", () => {
        interface Data {
            id: number;
            columns: Column[];
        }
        interface Column {
            value?: string | undefined;
        }
        const columnByIndex_ = (index: number) => O.optic<Data>().prop("columns").optional().at(index);
        const value_ = O.optic<Column>().prop("value").optional();

        it("add property to column", () => {
            const data: Data = { id: 1, columns: [{}] };
            const value = "value";

            const result = O.set(columnByIndex_(0).compose(value_))(value)(data);

            expect(result).toStrictEqual({ ...data, columns: [{ value }] });
        });
    });
```

However, the test fails with 
```diff
Error: expect(received).toStrictEqual(expected) // deep equality

- Expected  - 1
+ Received  + 1

  Object {
    "columns": Array [
      Object {
-       "value": "value",
+       "value": undefined,
      },
    ],
    "id": 1,
  }
```

Workaround:
```typescript
O.modify(columnByIndex_(0))((col) => ({ ...col, value }))(data);
```

Notes: 
* It does not matter how many properties already contained in the object itself. 
* Same behavior appears using `modify` instead of `set`

**Comment by akheron** [comment]
It should work if you remove `.optional()` from the latter lens.

The `optional` prism doesn’t have a focus in the data structure because the value is undefined, so it doesn’t write anything. If you don’t use `optional`, the `prop` lens focuses on the undefined value and writing happens.

As a side not, it’s incorrect to say that `set` and `modify` work differently in the two examples, because you’re using different optics in your examples. Trying to modify through the `columnByIndex_(0).compose(value_)` optic doesn’t do anything either, so `set` and `modify` actually work in the same way. 

Hope this helps!

**Comment by aaschmid** [comment]
Reading between the lines it still sounds a bit like a bug which should be fixed from my point of view (however, I am not an expert in functional programming paradigms).

Thanks anyways and for this helpful library.
