### ISSUE TITLE
[Feature] Data-first piping?

### ISSUE THREAD

**Issue by redbar0n** [akheron/optics-ts#260]
Here is a suggestion for a slight change to the API.

The current example from the Readme, as it is:

```ts
import * as O from 'optics-ts'

type Book = {
  title: string
  isbn: string
  author: {
    name: string
  }
}
const optic = O.optic_<Book>().prop('author').prop('name')

const input: Book = {
  title: "The Hitchhiker's Guide to the Galaxy",
  isbn: '978-0345391803',
  author: {
    name: 'Douglas Adams',
  },
}

O.get(optic)(input) // => "Douglas Adams"

O.set(optic)('Arthur Dent')(input)

O.modify(optic)((str) => str.length + 29)(input)
```

This is what it could read like, with a [data-first](https://www.javierchavarri.com/data-first-and-data-last-a-comparison/) API (like [ReScript](https://rescript-lang.org/) and the excellent [ts-belt](https://mobily.github.io/ts-belt/) lib by @mobily does):

```ts
import * as O from 'optics-ts'

type Book = {
  title: string
  isbn: string
  author: {
    name: string
  }
}
const authorNameOf = O.optic_<Book>().prop('author').prop('name')

const book: Book = {
  title: "The Hitchhiker's Guide to the Galaxy",
  isbn: '978-0345391803',
  author: {
    name: 'Douglas Adams',
  },
}

O.get(authorNameOf)(book) // => "Douglas Adams"

O.set(authorNameOf)(book)('Arthur Dent')

O.modify(authorNameOf)(book)((str) => str.length + 29)
```

Imho, such an API  would make it even more readable and approachable for newcomers.

Would such a data-first API be possible?

**Comment by akheron** [comment]
The article you linked covers the advantages of data-last APIs well. Data first mainly seems to aim for better type inference for _OCaml_. Rest is a matter of taste.

Curiously, ts-belt seems to provide both data-first and data-last APIs: uncurried functions take data first, curried take data last. If a curried function was data first, it would kill all possibilities for piping, because JS/TS don't have syntax support for it (whereas OCaml and Reason have).

I see changing to data-first would be a huge breaking change for cosmetic gains.
