### ISSUE TITLE
`remove` set object key to Symbol(__remove_me__)  and break Jest `toEqual`

### ISSUE THREAD

**Issue by lanyusan** [akheron/optics-ts#4]
When use Jest to test object manipulation with optics-ts, Jest reported that `remove` set object key to the `Symbol(__remove_me__)` so test failed.

`JSON.stringify` wouldn't print object key with the Symbol but Jest's `toEqual` would report error when compare it to object without the key.

Is it expected or a bug? I did a search and didn't find a well known symbol for remove me. Is it new standard?

**Comment by akheron** [comment]
The "remove me" symbol is an implementation detail of optics-ts. The TypeScript typings don't allow you to remove values through optics that don't support removing, so your tests should not pass because of compile error.

If you're project is using JavaScript instead of TypeScript, I recommend you to use the partial.lenses library instead.

**Comment by lanyusan** [comment]
I use typescript. then i will just use modify to set the key to undefined.

**Comment by lanyusan** [comment]
A second thought. When I use `remove`, the key is actually typed as `SomeType | undefined`. I don't need a removal that changes the object's data type. Would that break your code? 

> The "remove me" symbol is an implementation detail of optics-ts. The TypeScript typings don't allow you to remove values through optics that don't support removing, so your tests should not pass because of compile error.
> 
> If your project is using JavaScript instead of TypeScript, I recommend you to use the partial.lenses library instead.

**Comment by lanyusan** [comment]
One more use case, I also use remove on a record type, `Record<string, SomeType>`, to remove an index key. Would that be type safe to remove the key? I am not an expert of TS type system. Just some idea for your reference.

**Comment by akheron** [comment]
I'm afraid I don't understand the case where using remove "leaks" the remove me symbol to the result data structure. Could you provide a minimal code sample of a situation where this happens?

**Comment by lanyusan** [comment]
I actually used `any` and `as`. The reason is my data structure is a recursive tree, with a few different types of fields at each node. I need to dynamically build up the lens / prism for all the fields, and also recursively with arbitrary depth, based on conditions. 

So if to enforce type check, the code would be very verbose. This might be the reason to bring out this problem.

**Comment by akheron** [comment]
Yeah, the problem is that the `.path()` lens cannot be used with `O.remove()`, at least not yet. `.index()` is currently the only optic that supports removal, and it can only be used with arrays.

However, you can remove object fields with the `.pick()` lens by setting an object that doesn't contain the field you want to remove. It might not be optimal, but it's the only way as of now.

**Comment by akheron** [comment]
What comes to typing your recursive tree, with a few different types of fields at nodes, I suggest you to have look at discriminated unions (https://www.typescriptlang.org/docs/handbook/advanced-types.html#discriminated-unions), type guards (https://www.typescriptlang.org/docs/handbook/advanced-types.html#type-guards-and-differentiating-types), and perhaps the `.guard()` prism of optics-ts.

**Comment by lanyusan** [comment]
That's very helpful. Thanks.
